- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/msg.rs
- contracts/terraswap_pair/src/testing.rs
- packages/terraswap/src/lib.rs
- packages/terraswap/src/msg.rs
* Add optional argument `to` argument to `pair` contract
* Expose `pair` contract handle msg
> [Feature] Add optional argument `swap-to` 

- contracts/terraswap_factory/README.md
- contracts/terraswap_pair/README.md
- apply the correct param of assets
- remove unnecessary white space
> fix: execute params

- contracts/terraswap_pair/README.md
> [Docs] update readme for swap-to

- CHANGELOG.md
- Cargo.lock
- contracts/terraswap_router/Cargo.toml
- contracts/terraswap_router/schema/config_response.json
- contracts/terraswap_router/schema/cw20_hook_msg.json
- contracts/terraswap_router/schema/execute_msg.json
- contracts/terraswap_router/schema/instantiate_msg.json
- contracts/terraswap_router/schema/query_msg.json
- contracts/terraswap_router/src/contract.rs
- contracts/terraswap_router/src/operations.rs
- contracts/terraswap_router/src/state.rs
- contracts/terraswap_router/src/testing/tests.rs
- packages/terraswap/Cargo.toml
- packages/terraswap/src/router.rs
> feat: LOOP and ASTROPORT support on router

- contracts/terraswap_factory/src/contract.rs
- contracts/terraswap_factory/src/response.proto
- contracts/terraswap_factory/src/response.rs
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/response.proto
- contracts/terraswap_pair/src/response.rs
proto response changed for terra rebirth
----
> update proto response

- contracts/terraswap_pair/src/contract.rs
> fix: remove unnecessary validation

- .github/workflows/tests.yml
- README.md
> docs: add to codecov

- CHANGELOG.md
- contracts/terraswap_factory/src/contract.rs
- contracts/terraswap_factory/src/testing.rs
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_router/src/contract.rs
- contracts/terraswap_router/src/operations.rs
- packages/terraswap/README.md
- packages/terraswap/src/asset.rs
- packages/terraswap/src/mock_querier.rs
- packages/terraswap/src/querier.rs
- packages/terraswap/src/testing.rs
- packages/terraswap/src/token.rs
> Improved package test coverage

- CHANGELOG.md
- Cargo.lock
- contracts/terraswap_factory/Cargo.toml
- contracts/terraswap_factory/schema/execute_msg.json
- contracts/terraswap_factory/schema/query_msg.json
- contracts/terraswap_factory/src/contract.rs
- contracts/terraswap_factory/src/state.rs
- contracts/terraswap_factory/src/testing.rs
- contracts/terraswap_pair/Cargo.toml
- contracts/terraswap_router/Cargo.toml
- contracts/terraswap_router/src/testing/tests.rs
- contracts/terraswap_token/Cargo.toml
- packages/terraswap/Cargo.toml
- packages/terraswap/README.md
- packages/terraswap/src/asset.rs
- packages/terraswap/src/factory.rs
- packages/terraswap/src/mock_querier.rs
- packages/terraswap/src/querier.rs
- packages/terraswap/src/testing.rs
> feat: add native token decimals

- CHANGELOG.md
- Cargo.lock
- contracts/terraswap_factory/Cargo.toml
- contracts/terraswap_factory/src/contract.rs
- contracts/terraswap_factory/src/testing.rs
- contracts/terraswap_pair/Cargo.toml
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_router/Cargo.toml
- contracts/terraswap_router/src/contract.rs
- contracts/terraswap_token/Cargo.toml
- packages/terraswap/Cargo.toml
- packages/terraswap/src/factory.rs
> feat: support to migrate pair

- Cargo.lock
- contracts/terraswap_factory/src/state.rs
- contracts/terraswap_pair/Cargo.toml
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_router/src/state.rs
- packages/terraswap/src/asset.rs
- packages/terraswap/src/factory.rs
- packages/terraswap/src/pair.rs
- packages/terraswap/src/router.rs
> refactor: remove bigint dependecy

- Cargo.lock
- contracts/terraswap_pair/Cargo.toml
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
> fix: prevention of share calculation overflow

- contracts/terraswap_pair/README.md
- contracts/terraswap_pair/schema/execute_msg.json
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/testing.rs
- packages/terraswap/src/pair.rs
> feat: refund & desired asset to provide liqudity

- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/testing.rs
> refactor: decimal loss is paid by the user

- contracts/terraswap_pair/README.md
- contracts/terraswap_pair/schema/cw20_hook_msg.json
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
- contracts/terraswap_pair/src/testing.rs
- packages/terraswap/src/pair.rs
> feat: min_assets support when withdraw

- contracts/terraswap_pair/README.md
- contracts/terraswap_pair/schema/cw20_hook_msg.json
- contracts/terraswap_pair/schema/execute_msg.json
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
- contracts/terraswap_pair/src/testing.rs
- contracts/terraswap_router/schema/cw20_hook_msg.json
- contracts/terraswap_router/schema/execute_msg.json
- contracts/terraswap_router/src/contract.rs
- contracts/terraswap_router/src/operations.rs
- contracts/terraswap_router/src/testing/tests.rs
- packages/terraswap/src/pair.rs
- packages/terraswap/src/router.rs
> feat: deadline support for swap, provide and withdraw

- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
- contracts/terraswap_router/src/contract.rs
> refactor: maturity

- contracts/terraswap_pair/src/contract.rs
> refactor: define commission

- contracts/terraswap_pair/schema/execute_msg.json
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
- contracts/terraswap_pair/src/testing.rs
- packages/terraswap/src/pair.rs
> fix: revert slippage tolerance in provide liquidity

- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/error.rs
- contracts/terraswap_pair/src/testing.rs
> feat: initial liquidity deduction for pair protection

- Cargo.lock
- contracts/terraswap_factory/README.md
- contracts/terraswap_factory/schema/execute_msg.json
- contracts/terraswap_factory/src/contract.rs
- contracts/terraswap_factory/src/state.rs
- contracts/terraswap_factory/src/testing.rs
- contracts/terraswap_pair/README.md
- contracts/terraswap_pair/src/contract.rs
- contracts/terraswap_pair/src/testing.rs
- contracts/terraswap_router/src/contract.rs
- packages/terraswap/Cargo.toml
- packages/terraswap/schema/asset.json
- packages/terraswap/schema/asset_info.json
- packages/terraswap/schema/pair_info.json
- packages/terraswap/src/factory.rs
- packages/terraswap/src/lib.rs
- packages/terraswap/src/util.rs
> feat: create pair with provide liquidity
